### PR TITLE
[ReadModel] Add type to ElasticSearch query

### PR DESCRIPTION
**Pull request by manelephant**
Allowing to lock a specific ElasticSearch type when using search and
findBy methods of ES readModel repository

### CODE REVIEW

**Comment by rudott** [comment]
@wjzijderveld can you check this PR? I just tested this in our development environment and it works fine.

We need this for using the Elasticsearch repository + 1 index for multiple types.

Thanks!

**Comment by wjzijderveld** [comment]
Rebased en pushed to master in https://github.com/qandidate-labs/broadway/commit/c65103c15ba1048d8f72419a718f78cf51452e67

**Comment by wjzijderveld** [comment]
Thanks @manelephant

**Comment by manelephant** [comment]
Thanx for merging !

**Pull request closed without merging**
