### PR TITLE
Add associative keys to event arguments in EventDispatchingCommandBus

### PR DESCRIPTION
**Pull request by Xerkus**
This pull request adds associative keys to arguments in command failure event in EventDispatchingCommandBus to make it consistent with command success event

### CODE REVIEW

**Comment by sstok** [comment]
:+1:

**Comment by wjzijderveld** [comment]
Minor BC break, but :+1: from me :smile:

**Comment by tPl0ch** [comment]
@wjzijderveld Can you merge this? Then I could actually work on https://github.com/qandidate-labs/broadway/issues/199 by implementing it into the `EventDispatchingCommandBus`

**Comment by wjzijderveld** [comment]
Thanks @Xerkus !

**Pull request merged**
