### PR TITLE
Check for error responses from elasticsearch

### PR DESCRIPTION
**Pull request by richardmiller**
I ran into an issue where we were getting 401 responses back from elasticsearch because of the issue in #155. These were getting swallowed though so that it looked as though everything was ok but that no results were found. 

Not sure is this is an ideal way of dealing with this though.

### CODE REVIEW

**Comment by wjzijderveld** [comment]
Not sure about this way as well. But besides that: I'm not sure what happened actually, because as far as I can see (haven't tried to reproduce yet), elasticsearch client already throws exceptions and we only catch the 404's.

**Comment by richardmiller** [comment]
Will take another look, the elasticsearch client is not throwing an exception, so may well be a bug with that.

**Comment by asm89** [comment]
@richardmiller Did you manage to find anything?

**Comment by richardmiller** [comment]
Will close as I think this is an issue in the elasticsearch client

**Pull request closed without merging**
