### PR TITLE
Getter fot the AggregateRootInstance in the testing scenario

### PR DESCRIPTION
**Pull request by bartdezwaan**
This might be handy if you want to check that your apply methods did there job.

### CODE REVIEW

**Comment by wjzijderveld** [comment]
What is your use-case exactly?
Wondering because the scenario is used to test emitted events after an action, testing if your aggregate is in the correct state based on given events should be a separate test imo.

**Comment by bartdezwaan** [comment]
I do understand your thinking.
But the scenario tests are very descriptive. So I would prefer to use them even if I want to test the state of my aggregate. I see no reason why I wouldn't.

**Comment by asm89** [comment]
@bartdezwaan In the event sourced case I don't see much need for it? The idea is that you assert the events emitted and the intermediate state shouldn't really matter? Do you have an example of where you think it does?

If you have an aggregate root that is _not_ event sourced I see that this could be useful, but in that case I'm not sure if this testing scenario is of any help.

**Comment by bartdezwaan** [comment]
@asm89  I don't have a specific case.
But if I want to test my apply methods, I want to test them with an AR in different states.
Why not describe that states with the scenario functionality that is already there.

I just want my tests to read nicely.
If I am not able to use the scenario, I will have to build the AR myself or write a builder for it.

**Comment by wjzijderveld** [comment]
Closing this, as we don't see the use of this in an event-sourced context.

**Pull request closed without merging**
