### PR TITLE
Removed @internal from public method

### LINKED ISSUE #173: In the EventSourcedAggregateRoot the apply method is marked as internal
https://github.com/qandidate-labs/broadway/blob/26ab0d8e527c990169727a92d59faf24f0f256cd/src/Broadway/EventSourcing/EventSourcedAggregateRoot.php#L35

As you would use this from your aggregate, I don't see it as internal. Maybe we actually meant 'inheritDoc' there?

### PR DESCRIPTION
**Pull request by wjzijderveld**
Fixes #173

### CODE REVIEW

**Comment by simensen** [comment]
:+1:

**Comment by sstok** [comment]
:+1:

**Comment by cordoval** [comment]
happier IDE :+1:

**Comment by mbadolato** [comment]
:+1:

**Comment by othillo** [comment]
:+1:

**Pull request merged**
