### PR TITLE
fixed deprecation warnings

### PR DESCRIPTION
**Pull request by ged15**
ok this doesn't work on Symfony 2.3.* :/

### CODE REVIEW

**Comment by wjzijderveld** [comment]
Yeah, this definitely would be the easy fix. But as 2.3 still has support till May 2016 (and security patches till May 2017) we cannot just drop support for 2.3...

**Comment by ged15** [comment]
Definitely. Already looking into ways to solve this. Also into ways to execute builds with Symfony 2.3 and the latest version.

**Comment by wjzijderveld** [comment]
Cool, haven't got around doing that.

Most commonly used is something like this: https://github.com/hwi/HWIOAuthBundle/blob/master/.travis.yml#L15-L24

**Comment by wjzijderveld** [comment]
As this is not a permanent solution and Symfony 'fixed' the warnings now, I'll close this PR.

I think we still need to come with a solution to support 3.0, but let's think about a proper solution there.

**Pull request closed without merging**
