### PR TITLE
Rename the Event Sourcing repository's add() method to save().Fixes #114

### LINKED ISSUE #114: Renaming the add method on the AggregateRoot
Currently, you have to call the `add` method to save the uncommitted events of your aggregate root to the event store. it is called `add` because you add the events to the event store, but that name isn't very obvious when you want to save your aggregate.

Ideas for a better name are welcome!

### PR DESCRIPTION
**Pull request by mbadolato**
Per the discussion in #114, renames the ```add()``` method to ```save()```

### CODE REVIEW

**Comment by wjzijderveld** [comment]
:+1:

**Comment by asm89** [comment]
:+1:

**Comment by cordoval** [comment]
:+1: what is left for a quick merge? cc @wjzijderveld ?

**Comment by wjzijderveld** [comment]
Thanks @mbadolato 

@cordoval Lack of time :disappointed:

**Pull request merged**
